services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/log:/var/log/nginx
    environment:
      - TZ=${TZ}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "${WEB_PORT}:80"

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    environment:
      - TZ=${TZ}

  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_store:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  pgadmin:
    container_name: pgadmin
    image: elestio/pgadmin:latest
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - TZ=${TZ}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

volumes:
  db_store:
  pgadmin:
